from flask import Blueprint, jsonify, Response, request
from app.diagnostics import run_full_diagnostics, get_latest_diag_cache

events_bp = Blueprint("events", __name__)

@events_bp.route("/api/report/export", methods=["GET", "POST"])
def api_report_export():
    fmt = request.args.get("format", "markdown").lower()
    mask_ip = request.args.get("mask", "false").lower() == "true"
    
    latest = get_latest_diag_cache().get("result") or run_full_diagnostics("github.com")
    target = latest.get("target", "github.com")
    overall = latest.get("overall_status", "healthy")
    root_cause = latest.get("root_cause", "正常")
    
    server_ip = "37.114.48.47"
    if mask_ip:
        server_ip = "37.114.*.*"
        target = target.replace("37.114.48.47", "37.114.*.*")
        
    if fmt == "json":
        return jsonify(latest)
    elif fmt == "csv":
        csv_content = "Stage,Name,Status,DurationMS,Raw,Basis,Fix\n"
        for s in latest.get("stages", []):
            csv_content += f'"{s["stage"]}","{s["name"]}","{s["status"]}","{s["duration"]}","{s["raw"]}","{s["basis"]}","{s["fix"]}"\n'
        return Response(csv_content, mimetype="text/csv", headers={"Content-Disposition": f"attachment;filename=diag_report_{target}.csv"})
    elif fmt == "html":
        stages_rows = ""
        for s in latest.get("stages", []):
            st = str(s.get("status", "healthy")).lower()
            badge_cls = "status-healthy" if st == "healthy" else ("status-warning" if st == "warning" else "status-critical")
            stages_rows += f"""
            <tr>
                <td><b>Stage {s.get('stage')}</b></td>
                <td><b>{s.get('name')}</b></td>
                <td><span class="badge {badge_cls}">[ {st.upper()} ]</span></td>
                <td>{s.get('duration')} ms</td>
                <td class="mono">{s.get('raw')}</td>
            </tr>
            """
        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>NetWatch Diagnostic Telemetry Report - {target}</title>
    <style>
        body {{ background: #060907; color: #e2ece4; font-family: 'JetBrains Mono', monospace; padding: 40px; margin: 0; line-height: 1.6; }}
        .header {{ border-bottom: 2px solid #78E08F; padding-bottom: 15px; margin-bottom: 25px; }}
        h1 {{ margin: 0 0 10px 0; color: #78E08F; font-size: 1.5rem; }}
        .meta-grid {{ display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; background: #0b120d; padding: 20px; border-radius: 6px; border: 1px solid rgba(120,224,143,0.2); margin-bottom: 30px; }}
        .meta-item {{ font-size: 0.9rem; }}
        .meta-item span {{ color: #64756A; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid rgba(140,165,145,0.15); font-size: 0.88rem; }}
        th {{ background: #0b120d; color: #78E08F; font-size: 0.82rem; text-transform: uppercase; }}
        .badge {{ padding: 2px 6px; border-radius: 3px; font-weight: bold; font-size: 0.78rem; }}
        .status-healthy {{ border: 1px solid #78E08F; color: #78E08F; background: rgba(120,224,143,0.1); }}
        .status-warning {{ border: 1px solid #E7C66B; color: #E7C66B; background: rgba(231,198,107,0.1); }}
        .status-critical {{ border: 1px solid #F07878; color: #F07878; background: rgba(240,120,120,0.1); }}
        .mono {{ font-family: monospace; color: #69D6D0; }}
        .footer {{ margin-top: 40px; font-size: 0.8rem; color: #64756A; text-align: center; border-top: 1px solid rgba(140,165,145,0.1); padding-top: 20px; }}
        @media print {{ body {{ background: #fff; color: #000; padding: 0; }} .meta-grid {{ background: #f5f5f5; border: 1px solid #ccc; }} th {{ background: #eee; color: #000; }} }}
    </style>
</head>
<body>
    <div class="header">
        <h1>⚡ NETWATCH AUTONOMOUS DIAGNOSTIC REPORT</h1>
        <div>Generated by NetWatch Cyber Operations Platform v3.2</div>
    </div>
    <div class="meta-grid">
        <div class="meta-item"><span>TARGET:</span> <b>{target}</b></div>
        <div class="meta-item"><span>TIMESTAMP:</span> <b>{latest.get('timestamp')}</b></div>
        <div class="meta-item"><span>EGRESS IP:</span> <b>{server_ip}</b></div>
        <div class="meta-item"><span>OVERALL RATING:</span> <span class="badge status-healthy">[ {overall.upper()} ]</span></div>
        <div class="meta-item" style="grid-column: span 2;"><span>ROOT CAUSE:</span> <b>{root_cause}</b></div>
    </div>
    <h2>FULL 12-STAGE NETWORK DIAGNOSTICS</h2>
    <table>
        <thead>
            <tr>
                <th>Stage</th>
                <th>Diagnostic Name</th>
                <th>Status</th>
                <th>Duration</th>
                <th>Raw Telemetry Output</th>
            </tr>
        </thead>
        <tbody>
            {stages_rows}
        </tbody>
    </table>
    <div class="footer">
        NetWatch Operational Terminal Report &bull; Printable via Ctrl+P
    </div>
</body>
</html>"""
        return Response(html_content, mimetype="text/html")
    else:
        md = f"# Node Seeker 诊断报告\n\n"
        md += f"- **检测目标**: `{target}`\n"
        md += f"- **检测时间**: {latest.get('timestamp')}\n"
        md += f"- **出口 IP**: `{server_ip}`\n"
        md += f"- **总体评级**: `{overall.upper()}`\n"
        md += f"- **根因判定**: {root_cause}\n\n"
        md += "## 全链路 12 阶段测试明细\n\n"
        md += "| 阶段 | 名称 | 状态 | 耗时 | 探测结果 |\n|---|---|---|---|---|\n"
        for s in latest.get("stages", []):
            md += f"| {s['stage']} | {s['name']} | {s['status'].upper()} | {s['duration']}ms | {s['raw']} |\n"
        md += "\n---\n*Report generated by Node Seeker Autonomous Diagnostic Platform v4+*\n"
        return Response(md, mimetype="text/markdown", headers={"Content-Disposition": f"attachment;filename=diag_report_{target}.md"})
