from flask import Blueprint, jsonify, Response, request
from app.diagnostics import run_full_diagnostics, get_latest_diag_cache

events_bp = Blueprint("events", __name__)

@events_bp.route("/api/report/export", methods=["GET", "POST"])
def api_report_export():
    fmt = request.args.get("format", "markdown").lower()
    mask_ip = request.args.get("mask", "false").lower() == "true"
    
    latest = get_latest_diag_cache().get("result") or run_full_diagnostics("github.com")
    target = latest.get("target", "github.com")
    overall = latest.get("overall_status", "healthy")
    root_cause = latest.get("root_cause", "正常")
    
    server_ip = "37.114.48.47"
    if mask_ip:
        server_ip = "37.114.*.*"
        target = target.replace("37.114.48.47", "37.114.*.*")
        
    if fmt == "json":
        return jsonify(latest)
    elif fmt == "csv":
        csv_content = "Stage,Name,Status,DurationMS,Raw,Basis,Fix\n"
        for s in latest.get("stages", []):
            csv_content += f'"{s["stage"]}","{s["name"]}","{s["status"]}","{s["duration"]}","{s["raw"]}","{s["basis"]}","{s["fix"]}"\n'
        return Response(csv_content, mimetype="text/csv", headers={"Content-Disposition": f"attachment;filename=diag_report_{target}.csv"})
    else:
        md = f"# Node Seeker 诊断报告\n\n"
        md += f"- **检测目标**: `{target}`\n"
        md += f"- **检测时间**: {latest.get('timestamp')}\n"
        md += f"- **出口 IP**: `{server_ip}`\n"
        md += f"- **总体评级**: `{overall.upper()}`\n"
        md += f"- **根因判定**: {root_cause}\n\n"
        md += "## 全链路 12 阶段测试明细\n\n"
        md += "| 阶段 | 名称 | 状态 | 耗时 | 探测结果 |\n|---|---|---|---|---|\n"
        for s in latest.get("stages", []):
            md += f"| {s['stage']} | {s['name']} | {s['status'].upper()} | {s['duration']}ms | {s['raw']} |\n"
        md += "\n---\n*Report generated by Node Seeker Autonomous Diagnostic Platform v4+*\n"
        return Response(md, mimetype="text/markdown", headers={"Content-Disposition": f"attachment;filename=diag_report_{target}.md"})
